apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name(pv)
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/root/data/"

